### ISSUE TITLE
Snow can be bypassed with window.parent.alert(...)

### ISSUE THREAD

**Issue by rwaldron** [LavaMoat/snow#67]
Reproduce by running: 

```
window.parent.alert(1);
```

In https://lavamoat.github.io/snow/demo/

**Comment by weizman** [comment]
Can't seem to reproduce this successfully. Here are the steps I've taken:
1. visit https://lavamoat.github.io/snow/demo/
2. open console
3. paste payload above
4. press enter
Result: Snow successfully captures the `alert` attempt and logs it to console instead.
Would you mind helping me understand what I'm missing? A video or any other creative idea will be highly appreciated.

<img width="1015" alt="Screenshot 2023-01-24 at 22 49 01" src="https://user-images.githubusercontent.com/13243797/214408633-2d061636-9684-4705-8c81-669e20d715c3.png">

**Comment by rwaldron** [comment]
Yep, same environment issue I described in https://github.com/LavaMoat/snow/issues/68
