### ISSUE TITLE
Snow can be bypassed with postMessage from iframe by accessing event.source and event.currentTarget

### ISSUE THREAD

**Issue by rwaldron** [LavaMoat/snow#68]
Reproduce by running

```js
const handler = (event) => {
  event.currentTarget.alert(1)
  event.source.alert(1);
  window.removeEventListener('message', handler);
};

window.addEventListener('message', handler);

const iframe = document.createElement('iframe');

document.body.append(iframe);

const script = iframe.contentDocument.createElement('script');
script.textContent = `
  window.parent.postMessage(0, '*');
`;

iframe.contentDocument.body.append(script);
```

In https://lavamoat.github.io/snow/demo/

**Comment by weizman** [comment]
Can't seem to reproduce this successfully. Here are the steps I've taken:
1. visit https://lavamoat.github.io/snow/demo/
2. open console
3. paste payload above
4. press enter
Result: Snow successfully captures the `alert` attempt and logs it to console instead.
Would you mind helping me understand what I'm missing? A video or any other creative idea will be highly appreciated.

<img width="1026" alt="Screenshot 2023-01-24 at 22 50 04" src="https://user-images.githubusercontent.com/13243797/214408981-237899bb-f3d8-42ee-8273-cd448d76ac39.png">

**Comment by rwaldron** [comment]
I just realized that I hadn't refreshed the demo page, so my previous changes were still active in the global object. lol, realms are hard 🤦

**Comment by weizman** [comment]
lol, yea tell me about it. I feel like I'm closer to madness than adoption with this project tbh.
