### ISSUE TITLE
Bypass using object with no contentWindow

### ISSUE THREAD

**Issue by mmndaniel** [LavaMoat/snow#96]
```
var obj = document.createElement('object');
Object.defineProperty(obj, 'contentWindow', { value: null });
document.body.appendChild(obj);
obj.data = '/';
obj.contentDocument.defaultView.alert(1);
```
Basically workaround [`chromium_bug_workaround.js`](https://github.com/LavaMoat/snow/blob/e6359c3b9306de84c12b157e5de2bec80c74a3d1/src/chromium_bug_workaround.js#L21) :) should be easy to fix using [this](https://github.com/LavaMoat/snow/blob/e6359c3b9306de84c12b157e5de2bec80c74a3d1/src/natives.js#L162)

**Comment by weizman** [comment]
yea this doesn't seem to be a [chromium_bug_workaround.js](https://github.com/LavaMoat/snow/blob/e6359c3b9306de84c12b157e5de2bec80c74a3d1/src/chromium_bug_workaround.js#L21) problem even, there's just something off with reloading an already attached `object` to the same origin.. not sure why...

**Comment by weizman** [comment]
I'd expect the load listener to fire but with object it doesn't for some reaons

**Comment by mmndaniel** [comment]
Seems like this is the same root cause?
```
var d = document.createElement('div');
document.body.appendChild(d);
d.innerHTML = `<embed id="tst"></embed>`;
setTimeout(()=>{ tst.src='about:blank'; setTimeout(()=>frames[0].alert(1), 100);},100);
```

**Comment by weizman** [comment]
does [this](https://github.com/LavaMoat/snow/issues/96#issuecomment-1593354554) work for you on https://lavamoat.github.io/snow/demo/? @mmndaniel

**Comment by weizman** [comment]
researching https://github.com/LavaMoat/snow/issues/96#issue-1758952553 more i learned something sad about `object`s.
They behave different then iframes, changing their `data` prop resets the window to an `about:blank` window synchronously. if the prop was reseted to a "legit" url, the listener will fire afterwards, but that doesn't change the fact that this object resets synchronously to an about:blank window every time `data` prop is being set and its load event does not fire..
can't think of a solution other than hooking into attributes setting which is something i really don't want to get into...

**Comment by weizman** [comment]
Are they synchronous? Because if not they are no help unfortunately

**Comment by weizman** [comment]
yea I'm starting to recall these... I'd like to avoid that if possible :(

**Comment by weizman** [comment]
not scared of objects/embeds anymore thanks to #118
